FROM node:18-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/webpack/dist ./dist
EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]